FROM continuumio/anaconda3

RUN conda config --add channels conda-forge

RUN conda install nb_conda -y && conda install obspy -y

RUN conda install jupyter -y --quiet 

RUN conda install -c conda-forge jupyter_contrib_nbextensions && jupyter contrib nbextension install --user 

RUN rm -rf /root/.local/share/jupyter/nbextensions  

RUN conda install pytorch torchvision cuda80 -c soumith

RUN pip install tensorboardX

RUN pip install tensorflow

# Install GEOS library
RUN apt-get install binutils libproj-dev gdal-bin

RUN wget http://download.osgeo.org/geos/geos-3.4.2.tar.bz2 && \
    tar xjf geos-3.4.2.tar.bz2

RUN cd geos-3.4.2
	&& ./configur e
	&& make \\
	&& sudo make install
	&& cd ..


# Install Basemap 
RUN pip install https://github.com/matplotlib/basemap/archive/v1.0.7rel.tar.gz

EXPOSE 8888

WORKDIR /data

CMD jupyter notebook --notebook-dir=/data --ip='*' --allow-root --port=8888 --no-browser
